FROM golang:1.25-alpine AS build

RUN apk add --no-cache git
ARG MINIO_VERSION=RELEASE.2025-10-15T17-29-55Z
RUN go install -v "github.com/minio/minio@${MINIO_VERSION}"

FROM alpine:3.22

RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/minio /usr/local/bin/minio

ENTRYPOINT ["minio"]
CMD ["server", "/data"]
