import { createApp } from 'vue';
import {
  ElAlert,
  ElButton,
  ElCard,
  ElConfigProvider,
  ElDialog,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElLoading,
  ElOption,
  ElSelect,
  ElTable,
  ElTableColumn,
  ElTag,
  ElTooltip,
  ElUpload,
} from 'element-plus';
import {
  ArrowRight,
  ChatDotRound,
  CircleCheck,
  Collection,
  Connection,
  Delete,
  Document,
  EditPen,
  Files,
  Grid,
  InfoFilled,
  Loading,
  Lock,
  MagicStick,
  Message,
  MoreFilled,
  OfficeBuilding,
  Plus,
  Position,
  QuestionFilled,
  Refresh,
  Search,
  SwitchButton,
  Upload,
  UploadFilled,
  User,
} from '@element-plus/icons-vue';
import 'element-plus/dist/index.css';
import './style.css';
import App from './App.vue';

const app = createApp(App);
const components = [
  ElAlert,
  ElButton,
  ElCard,
  ElConfigProvider,
  ElDialog,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElOption,
  ElSelect,
  ElTable,
  ElTableColumn,
  ElTag,
  ElTooltip,
  ElUpload,
  ArrowRight,
  ChatDotRound,
  CircleCheck,
  Collection,
  Connection,
  Delete,
  Document,
  EditPen,
  Files,
  Grid,
  InfoFilled,
  Loading,
  Lock,
  MagicStick,
  Message,
  MoreFilled,
  OfficeBuilding,
  Plus,
  Position,
  QuestionFilled,
  Refresh,
  Search,
  SwitchButton,
  Upload,
  UploadFilled,
  User,
];
for (const component of components) {
  const name = component.name;
  if (name) app.component(name, component);
}
app.directive('loading', ElLoading.directive);
app.mount('#app');
